// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonAPI.DomainLayer;

namespace PokemonAPI.DomainLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200825175648_TrainerSeed")]
    partial class TrainerSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd539"),
                            Description = "Throws a sharp leaf at opponent.",
                            Name = "Leaf throw"
                        },
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd549"),
                            Description = "Hardens skin to repel enemy attacks.",
                            Name = "Harden"
                        });
                });

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd529"),
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("Generation")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559"),
                            Avatar = "https://i.pinimg.com/originals/3b/78/47/3b7847675982776e5219e12a680ecd84.png",
                            Generation = 0,
                            Height = 20f,
                            Name = "Bulbasaur",
                            Type = "Bug",
                            Weight = 110f
                        });
                });

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.PokemonAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonAbilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("312c1c87-75ba-48ea-b7a0-6a31c19dae91"),
                            AbilityId = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd539"),
                            PokemonId = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559")
                        },
                        new
                        {
                            Id = new Guid("49f2b00a-9a79-4cbe-8001-c82d0bedfaa1"),
                            AbilityId = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd549"),
                            PokemonId = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559")
                        });
                });

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00dc1dbd-4868-4b4a-934d-1d0b165ea104"),
                            FirstName = "Ash",
                            LastName = "Ketcham"
                        });
                });

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.Pokemon", b =>
                {
                    b.HasOne("PokemonAPI.DomainLayer.Entities.Trainer", "Trainer")
                        .WithMany("CaughtPokemons")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("PokemonAPI.DomainLayer.ValueObjects.BaseStat", "BaseStats", b1 =>
                        {
                            b1.Property<Guid>("PokemonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer");

                            b1.Property<int>("HealthPoints")
                                .HasColumnType("integer");

                            b1.Property<int>("SpecialAttack")
                                .HasColumnType("integer");

                            b1.Property<int>("SpecialDefense")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.HasKey("PokemonId");

                            b1.ToTable("Pokemons");

                            b1.WithOwner()
                                .HasForeignKey("PokemonId");

                            b1.HasData(
                                new
                                {
                                    PokemonId = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559"),
                                    Attack = 30,
                                    Defense = 20,
                                    HealthPoints = 100,
                                    SpecialAttack = 60,
                                    SpecialDefense = 50,
                                    Speed = 90
                                });
                        });
                });

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.PokemonAbility", b =>
                {
                    b.HasOne("PokemonAPI.DomainLayer.Entities.Ability", "Ability")
                        .WithMany("Pokemons")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.DomainLayer.Entities.Pokemon", "Pokemon")
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonAPI.DomainLayer.Entities.Trainer", b =>
                {
                    b.OwnsOne("PokemonAPI.DomainLayer.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("TrainerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("TrainerId");

                            b1.ToTable("Trainers");

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");

                            b1.HasData(
                                new
                                {
                                    TrainerId = new Guid("00dc1dbd-4868-4b4a-934d-1d0b165ea104"),
                                    City = "Bogota",
                                    HouseNumber = "10",
                                    Street = "Las Venturas"
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
